---
- hosts: all
  become: yes
  gather_facts: no
  vars:
          ansible_user: "cumulus"
          ansible_ssh_pass: "CumulusLinux!"
          ansible_become_pass: "CumulusLinux!"
  tasks:
    - name: Fetch ports.conf
      fetch: dest=save/{{ inventory_hostname }}/ports.conf src=/etc/cumulus/ports.conf flat=yes

    - name: Fetch interfaces Configuration
      fetch: dest=save/{{ inventory_hostname }}/interfaces src=/etc/network/interfaces flat=yes

    - name: Fetch FRR daemons file
      fetch: dest=save/{{ inventory_hostname }}/daemons src=/etc/frr/daemons flat=yes

    - name: Fetch frr.conf
      fetch: dest=save/{{ inventory_hostname }}/frr.conf src=/etc/frr/frr.conf flat=yes
